version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dough
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh

  frontend:
    build:
      context: ./frontend/my-app
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - postgres

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/dough
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    command: ["./wait-for-it.sh", "postgres:5432", "--", "uvicorn" , "app.main:app"]

volumes:
  db_data:
  db_test_data:
